### ISSUE TITLE
[Feature]: Allow all emails to login via email link

### ISSUE THREAD

**Issue by dreftas** [digifactory/filament-wildcard-login#6]
### What happened?

It would be nice to have options:
- Allow all emails to login via email link.
- or specify certain emails that MUST enter password and can't login via email link.

### How to reproduce the bug

-

### Package Version

1.0.1

### PHP Version

8.3

### Laravel Version

11

**Comment by dreftas** [comment]
Hey @mrk-j  and thanks for quick response. Unfortunately I can't make PR at this time, and this feature is not "deadly needed", so it would be nice to have when you will have some time to look into it :)

**Comment by s7thamon** [comment]
Just came upon this package, thought this idea would be great too. Passwordless login basically for any user. There were some packages for v2 that are out there but nothing for v3 yet.

**Comment by mrk-j** [comment]
I just created a PR adding the option to enable e-mail login for all users, please see #7.

@dreftas @s7thamon What do you think?

**Comment by m-bosch** [comment]
We just released the version 1.0.3 where this feature has been added.
